/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EthicsRouteImport } from './routes/ethics'
import { Route as FlyerRouteImport } from './routes/flyer'
import { Route as MethodsRouteImport } from './routes/methods'
import { Route as SopRouteImport } from './routes/sop'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EthicsRoute = EthicsRouteImport.update({
  id: '/ethics',
  path: '/ethics',
  getParentRoute: () => rootRouteImport,
} as any)
const FlyerRoute = FlyerRouteImport.update({
  id: '/flyer',
  path: '/flyer',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodsRoute = MethodsRouteImport.update({
  id: '/methods',
  path: '/methods',
  getParentRoute: () => rootRouteImport,
} as any)
const SopRoute = SopRouteImport.update({
  id: '/sop',
  path: '/sop',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ethics': typeof EthicsRoute
  '/flyer': typeof FlyerRoute
  '/methods': typeof MethodsRoute
  '/sop': typeof SopRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ethics': typeof EthicsRoute
  '/flyer': typeof FlyerRoute
  '/methods': typeof MethodsRoute
  '/sop': typeof SopRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ethics': typeof EthicsRoute
  '/flyer': typeof FlyerRoute
  '/methods': typeof MethodsRoute
  '/sop': typeof SopRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ethics' | '/flyer' | '/methods' | '/sop'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ethics' | '/flyer' | '/methods' | '/sop'
  id: '__root__' | '/' | '/ethics' | '/flyer' | '/methods' | '/sop'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EthicsRoute: typeof EthicsRoute
  FlyerRoute: typeof FlyerRoute
  MethodsRoute: typeof MethodsRoute
  SopRoute: typeof SopRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ethics': {
      id: '/ethics'
      path: '/ethics'
      fullPath: '/ethics'
      preLoaderRoute: typeof EthicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flyer': {
      id: '/flyer'
      path: '/flyer'
      fullPath: '/flyer'
      preLoaderRoute: typeof FlyerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/methods': {
      id: '/methods'
      path: '/methods'
      fullPath: '/methods'
      preLoaderRoute: typeof MethodsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sop': {
      id: '/sop'
      path: '/sop'
      fullPath: '/sop'
      preLoaderRoute: typeof SopRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EthicsRoute: EthicsRoute,
  FlyerRoute: FlyerRoute,
  MethodsRoute: MethodsRoute,
  SopRoute: SopRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
